security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        ContinuezLHistoire\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_AUTEUR
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /accueil
            logout:
                path:   fos_user_security_logout
                target: /accueil
            remember_me:
                key:        %secret%

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
