parameters:
#    continuez_l_histoire_site.example.class: ContinuezLHistoire\SiteBundle\Example

#services:
#    continuezlhistoire_user.registration_complet:
#        class: ContinuezLHistoire\UserBundle\EventListener\RegistrationConfirmListener
#        arguments: [@router]
#        tags:
#          - { name: kernel.event_subscriber }
#    continuez_l_histoire_site.example:
#        class: %continuez_l_histoire_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
