<?php

namespace ContinuezLHistoire\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AvisUtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisUtilisateurRepository extends EntityRepository
{
}
