<?php

namespace ContinuezLHistoire\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SousHistoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousHistoireRepository extends EntityRepository
{
}
